import{a as h,i as n,S as b}from"./assets/vendor-mdVVRe9K.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const w="46051514-586eb2ff38120a16ff3b43d50",S="https://pixabay.com/api/";async function L(s,r=1,i=15){try{const o=await h.get(S,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i}});return{hits:o.data.hits,totalHits:o.data.totalHits}}catch(o){throw console.error("Error fetching images:",o),new Error("Sorry, there was an error fetching images. Please try again later.")}}function q(s){const r=document.querySelector(".gallery"),i=s.map(({webformatURL:o,largeImageURL:e,tags:t,likes:a,views:y,comments:p,downloads:g})=>`
    <a class="gallery-item" href="${e}">
      <div class="photo-card">
        <img src="${o}" alt="${t}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${a}</p>
          <p class="info-item"><b>Views:</b> ${y}</p>
          <p class="info-item"><b>Comments:</b> ${p}</p>
          <p class="info-item"><b>Downloads:</b> ${g}</p>
        </div>
      </div>
    </a>`).join("");r.insertAdjacentHTML("beforeend",i)}const v=document.querySelector("#search-form"),m=document.querySelector("#gallery"),d=document.querySelector(".loader"),l=document.querySelector("#load-more");let u=1,c="";v.addEventListener("submit",E);l.addEventListener("click",P);async function E(s){if(s.preventDefault(),m.innerHTML="",c=s.target.elements["search-query"].value.trim(),u=1,c===""){n.error({title:"Error",message:"Please enter a search query!"});return}l.style.display="none",await f(c)}async function f(s){d.style.display="block";try{const{hits:r,totalHits:i}=await L(s,u,15);if(d.style.display="none",r.length===0){n.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l.style.display="none";return}q(r),new b(".gallery a").refresh(),n.success({title:"Success",message:`Found ${i} images!`,position:"topRight"}),u*15<i?l.style.display="block":(l.style.display="none",n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const e=m.lastElementChild;if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}catch(r){d.style.display="none",n.error({title:"Error",message:r.message,position:"topRight"})}}async function P(){u+=1,await f(c)}
//# sourceMappingURL=index.js.map
